---
name: release

on:
  push:
    # branches:
    #   - develop
    tags:
      - "v*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # See: https://goreleaser.com/ci/actions/

      - id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true
      - name: Lookup Go cache directory
        id: go-cache
        run: |
          echo "dir=$(go env GOCACHE)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            go${{ steps.setup-go.outputs.go-version }}-"
        with:
          path: |
            ${{ steps.go-cache.outputs.dir }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('go.mod') }}-\
            ${{ hashFiles('go.sum') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
